### ISSUE TITLE
Using with Firebase

### ISSUE THREAD

**Issue by yun-cheng** [eneural-net/async_task#10]
Hi! I want to use Firebase in AsyncTask.
Does it support this usage?
Because I'm having problem with it.
Can I add `WidgetsFlutterBinding.ensureInitialized()` in AsyncTask `run` method?

**Comment by gmpassos** [comment]
I never used Firebase with Dart.

It all depends if the Firebase package for Dart supports multiple "Isolate"s.

**Comment by yun-cheng** [comment]
https://github.com/FirebaseExtended/flutterfire/issues/3124#issuecomment-726007838
This comment says adding `WidgetsBinding.ensureInitialized();` in isolate before using Firebase should work.

https://github.com/FirebaseExtended/flutterfire/issues/3124#issuecomment-729787901
Also, this comment says flutter_isolate and isolate_handler package supports calling that function.

But when I tried calling it in AsyncTask `run` method, it failed:
```
E/flutter (22300): [ERROR:flutter/runtime/dart_isolate.cc(1148)] Unhandled exception:
E/flutter (22300): UI actions are only available on root isolate.
E/flutter (22300): #0      PlatformDispatcher._nativeSetNeedsReportTimings (dart:ui/platform_dispatcher.dart:446:59)
E/flutter (22300): #1      PlatformDispatcher.onReportTimings= (dart:ui/platform_dispatcher.dart:438:29)
E/flutter (22300): #2      SingletonFlutterWindow.onReportTimings= (dart:ui/window.dart:540:24)
E/flutter (22300): #3      SchedulerBinding.addTimingsCallback
package:flutter/…/scheduler/binding.dart:265
E/flutter (22300): #4      SchedulerBinding.initInstances
package:flutter/…/scheduler/binding.dart:205
E/flutter (22300): #5      ServicesBinding.initInstances
package:flutter/…/services/binding.dart:31
E/flutter (22300): #6      PaintingBinding.initInstances
package:flutter/…/painting/binding.dart:22
E/flutter (22300): #7      SemanticsBinding.initInstances
package:flutter/…/semantics/binding.dart:22
E/flutter (22300): #8      RendererBinding.initInstances
package:flutter/…/rendering/binding.dart:28
E/flutter (22300): #9      WidgetsBinding.initInstances
package:flutter/…/widgets/binding.dart:277
E/flutter (22300): #10     new BindingBase
package:flutter/…/foundation/binding.dart:56
E/flutter (22300): #11     new _WidgetsFlutterBinding&BindingBase&GestureBinding (package:flutter/src/widgets/binding.dart)
package:flutter/…/widgets/binding.dart:1
E/flutter (22300): #12     new _WidgetsFlutterBinding&BindingBase&GestureBinding&SchedulerBinding (package:flutter/src/widgets/binding.dart)
package:flutter/…/widgets/binding.dart:1
E/flutter (22300): #13     new _WidgetsFlutterBinding&BindingBase&GestureBinding&SchedulerBinding&ServicesBinding (package:flutter/src/widgets/binding.dart)
package:flutter/…/widgets/binding.dart:1
E/flutter (22300): #14     new _WidgetsFlutterBinding&BindingBase&GestureBinding&SchedulerBinding&ServicesBinding&PaintingBinding (package:flutter/src/widgets/binding.dart)
package:flutter/…/widgets/binding.dart:1
E/flutter (22300): #15     new _WidgetsFlutterBinding&BindingBase&GestureBinding&SchedulerBinding&ServicesBinding&PaintingBinding&SemanticsBinding (package:flutter/src/widgets/binding.dart)
package:flutter/…/widgets/binding.dart:1
E/flutter (22300): #16     new _WidgetsFlutterBinding&BindingBase&GestureBinding&SchedulerBinding&ServicesBinding&PaintingBinding&SemanticsBinding&RendererBinding (package:flutter/src/widgets/binding.dart)
package:flutter/…/widgets/binding.dart:1
E/flutter (22300): #17     new _WidgetsFlutterBinding&BindingBase&GestureBinding&SchedulerBinding&ServicesBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding (package:flutter/src/widgets/binding.dart)
package:flutter/…/widgets/binding.dart:1
E/flutter (22300): #18     new WidgetsFlutterBinding (package:flutter/src/widgets/binding.dart)
package:flutter/…/widgets/binding.dart:1
E/flutter (22300): #19     WidgetsFlutterBinding.ensureInitialized
package:flutter/…/widgets/binding.dart:1252
E/flutter (22300): #20     PrimeChecker.run
package:try_widget_only/main.dart:87
E/flutter (22300): #21     AsyncTask.execute
package:async_task/src/async_task_base.dart:99
E/flutter (22300): #22     _Isolate._processTaskExecute
package:async_task/src/async_task_isolate.dart:979
E/flutter (22300): #23     _Isolate._processTask
package:async_task/src/async_task_isolate.dart:826
E/flutter (22300): #24     _Isolate._onMessage
package:async_task/src/async_task_isolate.dart:766
E/flutter (22300): #25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)

```

So I'm wondering is there a way to calling it?

**Comment by gmpassos** [comment]
I think that "WidgetsFlutterBinding.ensureInitialized" can only be called by the main Isolate, where you create the "AsyncExecutor" (not inside the task).

**Comment by yun-cheng** [comment]
In the flutter_isolate package's README it says:

> FlutterIsolate allows creation of an Isolate in flutter that is able to use flutter plugins. It creates the necessary platform specific bits (FlutterBackgroundView on android & FlutterEngine on iOS) to enable the platform channels to work inside an isolate.

So it would be nice to have this feature in async_task package.
Or is there a workaround for this?

**Comment by gmpassos** [comment]
I will take a look into "FlutterIsolate". For now async_task is Dart generic: it work in Flutter without any specific Flutter code.
